name: webassembly port
on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'ports/webassembly/**'
      - 'tests/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install packages
        run: source tools/ci.sh && ci_webassembly_setup

      - name: Build
        run: source tools/ci.sh && ci_webassembly_build

      - name: Run tests
        run: source tools/ci.sh && ci_webassembly_run_tests

      - name: Print failures
        if: failure()
        run: tests/run-tests.py --print-failures

      - name: List build outputs
        run: |
          echo "Searching for .wasm and .js files..."
          find ports/webassembly -type f -name "micropython.*" || true

      - name: Upload WebAssembly artifacts
        uses: actions/upload-artifact@v4
        with:
          name: micropython-wasm
          path: ports/webassembly/build-*/micropython.*
